2023-11-30 18:40:23,802 INFO : Traitement du fichier files/Client.xml
2023-11-30 18:40:24,651 INFO : Traitement terminé
2023-11-30 18:42:38,948 INFO : Traitement du fichier files/Client.xml
2023-11-30 18:42:39,705 INFO : Traitement terminé
2023-11-30 18:45:35,467 INFO : Traitement du fichier files/Client.xml
2023-11-30 18:45:36,267 ERROR : cannot access local variable 'f' where it is not associated with a value
Traceback (most recent call last):
  File "E:\PROJETS\SABC\DbIntegrator\main.py", line 75, in run
    self.create_xml(tagIndex, value, val_array, name_array, file)
  File "E:\PROJETS\SABC\DbIntegrator\main.py", line 107, in create_xml
    f.write(xml_str)
    ^
UnboundLocalError: cannot access local variable 'f' where it is not associated with a value
2023-11-30 18:46:54,717 INFO : Traitement du fichier files/Client.xml
2023-11-30 18:46:55,526 ERROR : cannot access local variable 'f' where it is not associated with a value
Traceback (most recent call last):
  File "E:\PROJETS\SABC\DbIntegrator\main.py", line 77, in run
    self.create_xml(tagIndex, value, val_array, name_array, file)
  File "E:\PROJETS\SABC\DbIntegrator\main.py", line 109, in create_xml
    f.write(xml_str)
    ^
UnboundLocalError: cannot access local variable 'f' where it is not associated with a value
2023-11-30 18:47:01,033 INFO : Traitement du fichier files/Client.xml
2023-11-30 18:47:01,864 ERROR : cannot access local variable 'f' where it is not associated with a value
Traceback (most recent call last):
  File "E:\PROJETS\SABC\DbIntegrator\main.py", line 77, in run
    self.create_xml(tagIndex, value, val_array, name_array, file)
  File "E:\PROJETS\SABC\DbIntegrator\main.py", line 109, in create_xml
    f.write(xml_str)
    ^
UnboundLocalError: cannot access local variable 'f' where it is not associated with a value
2023-11-30 18:47:12,205 INFO : Traitement du fichier files/Client.xml
2023-11-30 18:47:12,988 ERROR : cannot access local variable 'f' where it is not associated with a value
Traceback (most recent call last):
  File "E:\PROJETS\SABC\DbIntegrator\main.py", line 77, in run
    self.create_xml(tagIndex, value, val_array, name_array, file)
  File "E:\PROJETS\SABC\DbIntegrator\main.py", line 109, in create_xml
    f.write(xml_str)
    ^
UnboundLocalError: cannot access local variable 'f' where it is not associated with a value
2023-11-30 20:50:04,735 INFO : Traitement du fichier files/Client.xml
2023-11-30 20:50:04,854 ERROR : cannot access local variable 'category_array' where it is not associated with a value
Traceback (most recent call last):
  File "E:\PROJETS\SABC\DbIntegrator\main.py", line 60, in run
    print(category_array)
          ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'category_array' where it is not associated with a value
2023-11-30 20:50:29,584 INFO : Traitement du fichier files/Client.xml
2023-11-30 20:50:29,649 ERROR : cannot access local variable 'category_array' where it is not associated with a value
Traceback (most recent call last):
  File "E:\PROJETS\SABC\DbIntegrator\main.py", line 60, in run
    print(category_array)
          ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'category_array' where it is not associated with a value
2023-11-30 20:50:46,778 INFO : Traitement du fichier files/Client.xml
2023-11-30 20:50:46,837 ERROR : cannot access local variable 'category_array' where it is not associated with a value
Traceback (most recent call last):
  File "E:\PROJETS\SABC\DbIntegrator\main.py", line 60, in run
    print(category_array)
          ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'category_array' where it is not associated with a value
2023-11-30 20:51:03,515 INFO : Traitement du fichier files/Client.xml
2023-11-30 20:51:03,612 ERROR : cannot access local variable 'category_array' where it is not associated with a value
Traceback (most recent call last):
  File "E:\PROJETS\SABC\DbIntegrator\main.py", line 60, in run
    print(category_array)
          ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'category_array' where it is not associated with a value
2023-11-30 20:51:05,321 INFO : Traitement du fichier files/Client.xml
2023-11-30 20:51:05,406 ERROR : cannot access local variable 'category_array' where it is not associated with a value
Traceback (most recent call last):
  File "E:\PROJETS\SABC\DbIntegrator\main.py", line 60, in run
    print(category_array)
          ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'category_array' where it is not associated with a value
